spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: customer-service
              uri: lb://CUSTOMER-SERVICE
              predicates:
                - Path=/api/customers/**
            - id: product-service
              uri: lb://INVENTORY-SERVICE
              predicates:
                - Path=/api/products/**