spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: customer-service
              uri: http://localhost:8081
              predicates:
                - Path = /customers/**
            - id: product-service
              uri: http://localhost:8082
              predicates:
                - Path = /products/**